### ISSUE TITLE
该更新了 大佬

### ISSUE THREAD

**Issue by alonedogboy** [kwxos/CF-Ali-DNSpod-ddns-IP#2]

**Comment by IonRh** [comment]
好，从厂里回来了，后面更新

**Comment by jiayihello** [comment]
静候，前几天微信支持了一下😄😄😄

**Comment by IonRh** [comment]
![image](https://github.com/kwxos/CF-Ali-DNSpod-ddns-IP/assets/102129419/e4b62d39-024f-4378-a6a3-79f6dabb7455)
本来以为回来就有空整了，没想到事还是多的很，多IP更新到cf的搞了一半，哎，一些事搞得我要烦死了

**Comment by IonRh** [comment]
> 静候，前几天微信支持了一下😄😄😄
感谢感谢，我前几天一直在兼职，手机看不了，也没注意，不好意思不好意思

**Comment by IonRh** [comment]
已更新

**Comment by IonRh** [comment]
> 静候，前几天微信支持了一下😄😄😄

已更新
